# see https://prometheus.io/docs/operating/configuration/
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - localhost:9090
  - job_name: 'windows'
    static_configs:
      - targets:
        - localhost:9182
